apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.config.prefix }}
  name: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-{{ .Values.config.prefix }}-humio-ingest
{{ else }}
  name: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-humio-ingest
{{- end }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    strimzi.io/cluster: {{ .Values.config.clusterName }}
    {{- include "logscale-strimzi-kafka-topics.labels" . | nindent 4 }}
spec:
{{- if .Values.config.prefix }}
  topicName: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-{{ .Values.config.prefix }}-humio-ingest
{{ else }}
  topicName: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-humio-ingest
{{- end }}
  partitions: {{ .Values.config.topics.ingest.digestPartitionsCount }}
  replicas: {{ .Values.config.topics.ingest.replicas }}
  config:
    cleanup.policy: "delete"
    compression.type: producer
    min.insync.replicas: {{ .Values.config.topics.ingest.minisr }}
    retention.ms: {{ .Values.config.topics.ingest.retention.ms }}
    retention.bytes: {{ .Values.config.topics.ingest.retention.bytes }}
    max.message.bytes: 10485760
