apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.config.prefix }}
  name: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-{{ .Values.config.prefix }}-global-events
{{ else }}
  name: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-global-events
{{- end }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    strimzi.io/cluster: {{ .Values.config.clusterName }}
    {{- include "logscale-strimzi-kafka-topics.labels" . | nindent 4 }}
spec:
{{- if .Values.config.prefix }}
  topicName: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-{{ .Values.config.prefix }}-global-events
{{ else }}
  topicName: {{ include "logscale-strimzi-kafka-topics.fullname" . }}-global-events
{{- end }}
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: "delete"
    compression.type: producer
    min.insync.replicas: 2
    max.message.bytes: 2097152
    retention.bytes: 1073741824
    retention.ms: -1
