# Default values for logscale-strimiz-kafka-topics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

keep: true

config:
  topics:
    ingest:
      digestPartitionsCount: 480
      minisr: 2
      # Two(2) days x 86400 * 1000
      retention:
        ms: 172800000
        bytes: -1
