watchAnyNamespace: true
createAggregateRoles: true
resources:
  requests:
    cpu: 50m
    memory: 384Mi
  limits:
    cpu: "500m"
    memory: 512Mi
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
