# Default values for logscale-strimzi-kafka-topics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

keep: true

config:
  user:
    enabled: true
    authentication:
      type: tls-external
    authorization:
      type: simple
  topics:
    ingest:
      replicas: 3
      digestPartitionsCount: 480
      minisr: 2
      # Two(2) days x 86400 * 1000
      retention:
        ms: 172800000
        bytes: -1
    global:
      replicas: 3
      minisr: 2
    transientChatter:
      replicas: 3
      minisr: 2
